baseurl: "/Haal-Centraal"
apiname: "Haal Centraal Landingspagina"
url: "http://localhost:4000"
plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: VNG-Realisatie/jekyll-theme-haal-centraal

github: VNG-Realisatie/Haal-Centraal

theme: jekyll-theme-time-machine

project_name: /Haal-Centraal
